version: "3"
services:
  bdusupport_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    environment:
      - DATABASE_ENGINE=mysql
      - DATABASE_NAME=bdusupport
      - DATABASE_USERadmin
      - DATABASE_PASSWORD=@YrMIZvx$_Y3(u
      - DATABASE_HOST=192.168.69.28
      - DATABASE_PORT=3306
      - REDIS_HOST=192.168.69.28
      - REDIS_PORT=6380
      - REDIS_USERNAME=""
      - REDIS_PASSWORD=""
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=""
      - EMAIL_HOST_PASSWORD=""
      - FIREBASE_CERTIFICATE=/usr/src/app/firebase_cert.json
      - FIREBASE_STORAGE_BUCKET_URL=gs://bdusupport.appspot.com
    volumes:
      - ./:/usr/src/app

volumes:
  mysql_data:
  redis_data:
