version: "3"
services:
  bdusupport_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    environment:
      - DATABASE_ENGINE=mysql
      - DATABASE_NAME=bdusupport
      - DATABASE_USER=root
      - DATABASE_PASSWORD=bdusupport
      - DATABASE_HOST=bdusupport_mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=bdusupport_redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=""
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER="ntt06012k2@gmail.com"
      - EMAIL_HOST_PASSWORD="ntav gnas vdmt rkpk"
      - FIREBASE_CERTIFICATE=/usr/src/app/firebase_cert.dev.json
      - FIREBASE_STORAGE_BUCKET_URL=super-system-65cf5.appspot.com
      - BETTERSTACK_LOG_TOKEN=RBoHWYbFThGsSkXKkZwc9hKP
    depends_on:
      - bdusupport_mysql
      - bdusupport_redis

  bdusupport_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    environment:
      - DATABASE_ENGINE=mysql
      - DATABASE_NAME=bdusupport
      - DATABASE_USER=root
      - DATABASE_PASSWORD=bdusupport
      - DATABASE_HOST=bdusupport_mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=bdusupport_redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=""
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER="ntt06012k2@gmail.com"
      - EMAIL_HOST_PASSWORD="ntav gnas vdmt rkpk"
      - FIREBASE_CERTIFICATE=/usr/src/app/firebase_cert.dev.json
      - FIREBASE_STORAGE_BUCKET_URL=super-system-65cf5.appspot.com
      - BETTERSTACK_LOG_TOKEN=RBoHWYbFThGsSkXKkZwc9hKP
    depends_on:
      - bdusupport_mysql
      - bdusupport_redis
  
  bdusupport_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "bdusupport"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "bdusupport"
      MYSQL_ROOT_PASSWORD: "bdusupport"
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  bdusupport_redis:
    image: redis:6.0
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: